server:
  port: 8083

spring:
  application:
    name: business-service
  datasource:
    url: jdbc:postgresql://localhost:5432/arterp_business
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

jwt:
  secret: arterp-secret-key-must-be-very-long-and-secure-in-production
  expiration: 86400 